name: Update ICS File

on:
  schedule:
  - cron: '*/5 * * * *'  # every 5 minutes (maximum reliable frequency)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python docs/fix_calendar.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/fixed_calendar.ics
          git commit -m "Update fixed calendar" || echo "No changes"
          git push
